name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: brew install openssl
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -Y
      - run: nimble test
