name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openssl
          echo "NIM_PASSL=--passL:-L$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
      - uses: georgelemon/setup-nim-action@master # jiro4989/setup-nim-action@v2 # georgelemon/setup-nim-action@master for getting the prebuilt from homebrews
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -Y $NIM_PASSL
        shell: bash
      - run: nimble test $NIM_PASSL
        shell: bash
